spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:              
              metadata-uri: https://dev-72791896.okta.com/app/exk93zh00ia422VfO5d7/sso/saml/metadata
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"          
          bcit:
            assertingparty:              
              metadata-uri: classpath:metadata/metadata-idp.xml
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"    
logging:
  level:
    '[org.springframework.security.saml2]':
      debug 